openapi: 3.0.0
info:
  title: Asistente API - Integración Sabi
  description: API que integra sistemas Sabi mediante IA (Claude y Gemini)
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Servidor local
  - url: https://sabi.bispace.site
    description: Servidor Sabi production

paths:
  /api/chat:
    post:
      summary: Consultar información sobre APIs Sabi
      description: Endpoint para hacer preguntas sobre la API de Sabi usando Claude o Gemini
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  example: "¿Cómo crear un nuevo usuario en Sabi?"
                model:
                  type: string
                  enum: [claude, gemini]
                  default: claude
                apiSources:
                  type: array
                  items:
                    type: string
                    enum: [sabi, swagger]
                  default: [sabi]
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  question:
                    type: string
                  answer:
                    type: string
                  model:
                    type: string
                  sources:
                    type: array
                    items:
                      type: string
                  timestamp:
                    type: string
                    format: date-time

  /api/mcp/sabi/{endpoint}:
    get:
      summary: Acceder a endpoints específicos de Sabi
      parameters:
        - name: endpoint
          in: path
          required: true
          schema:
            type: string
            example: "users"
      responses:
        '200':
          description: Datos de Sabi API
        '500':
          description: Error al acceder a Sabi API